## https://mherman.org/blog/dockerizing-a-react-app/
version: "3"
services:
  react:
    container_name: "ts-react"
    image: "ts-react:development"
    volumes:
      - ./src:/app/src
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:3000"
    env_file:
      - ".env.development"
    environment:
      ENV: "development"
      REACT_APP_API: "http://localhost:1234/graphql"
      REACT_APP_APP_NAME: "Cloture"
      REACT_APP_GOOGLE_ANALYTICS: "123"
    stdin_open: true
